if not Config then Config = {} end

-- Language Configuration
-- Change the value (right side) as needed. Do not change the key (left side).
-- Keep the %{value} placeholders intact.
Config.Lang = {
    -- Lua-side (notifications)
    ['crosshair_on']       = 'Custom crosshair enabled.',
    ['crosshair_off']      = 'Custom crosshair disabled.',
    ['settings_reset']     = 'Crosshair reset to defaults.',
    ['preset_applied']     = 'Preset applied: %{name}',
    ['profile_saved']      = 'Profile saved: %{name}',
    ['profile_loaded']     = 'Profile loaded: %{name}',
    ['profile_deleted']    = 'Profile deleted: %{name}',
    ['profile_limit']      = 'Profile limit reached (%{max}). Delete one first.',
    ['import_ok']          = 'Crosshair imported.',
    ['import_invalid']     = 'Import failed: that is not a valid crosshair code.',
    ['admin_denied']       = 'You are not allowed to open the crosshair admin panel.',
    ['admin_saved']        = 'Crosshair config saved and applied to everyone.',

    -- NUI: chrome / shell
    ['ui_title']           = 'Crosshair',
    ['ui_subtitle']        = 'Maker',
    ['ui_to_close']        = 'to close',
    ['ui_on']              = 'On',
    ['ui_off']             = 'Off',
    ['ui_saved']           = 'Saved',
    ['ui_saving']          = 'Saving…',
    ['ui_reset']           = 'Reset',
    ['ui_reset_confirm_title'] = 'Reset crosshair?',
    ['ui_reset_confirm_body']  = 'Everything goes back to the default crosshair. Your saved profiles are kept.',
    ['ui_cancel']          = 'Cancel',
    ['ui_apply']           = 'Apply',
    ['ui_keybind_hint']    = 'rebindable in GTA settings',
    ['ui_keybind_none']    = 'unbound',

    -- NUI: sections
    ['ui_sections']        = 'Sections',
    ['ui_sec_general']     = 'General',
    ['ui_sec_general_sub'] = 'Visibility, behaviour and keybinds.',
    -- Style is one tab: shape, colors, outline and the center dot. The two
    -- ui_sec_colors / ui_sec_dot keys below now label cards inside it.
    ['ui_sec_style_sub']   = 'Shape, colors and the center dot.',
    ['ui_sec_scope_sub']   = 'Sniper-style overlay with mouse-wheel zoom.',
    ['ui_sec_profiles_sub'] = 'Presets, saved profiles and share codes.',
    ['ui_keybinds']        = 'Keybinds',
    ['ui_reticle']         = 'Reticle',
    ['ui_scope_off_preview'] = 'Scope is OFF',

    -- NUI: per-weapon rules
    ['ui_sec_weapons']     = 'Per Weapon',
    ['ui_sec_weapons_sub'] = 'A different crosshair per weapon type.',
    ['ui_perweapon_enable'] = 'Per-weapon crosshairs',
    ['ui_perweapon_enable_hint'] = 'Assign saved profiles to weapon types. Types left on Main use your main crosshair.',
    ['ui_pw_default']      = 'Main crosshair',
    ['ui_pw_hidden']       = 'Hidden',
    ['ui_pw_missing']      = 'profile was deleted',
    ['ui_pw_note']         = 'Save profiles in the Profiles tab to assign them here.',
    ['ui_pw_current']      = 'holding now',
    ['ui_pw_off']          = 'Per-weapon crosshairs are off. Turn them on above to assign a profile to each weapon class.',

    -- NUI: share codes
    ['ui_code_title']      = 'Crosshair code',
    ['ui_code_hint']       = 'Short code, like CS2: copy it and send it to a friend.',
    ['ui_code_profile_tip'] = 'Copy this profile\'s code',
    ['ui_sec_style']       = 'Style',
    ['ui_sec_colors']      = 'Colors',
    ['ui_sec_dot']         = 'Center Dot',
    ['ui_sec_scope']       = 'Scope',
    ['ui_sec_profiles']    = 'Profiles',

    -- NUI: general
    ['ui_enabled']         = 'Crosshair enabled',
    ['ui_enabled_hint']    = 'Master switch. The keybind below flips this too.',
    ['ui_show_mode']       = 'Show crosshair',
    ['ui_show_mode_hint']  = 'When the crosshair is visible on screen.',
    ['ui_mode_always']     = 'Always',
    ['ui_mode_armed']      = 'When armed',
    ['ui_mode_aiming']     = 'While aiming',
    ['ui_hide_vehicle']    = 'Hide in vehicles',
    ['ui_hide_vehicle_hint'] = 'Hide the crosshair while you sit in a vehicle.',
    ['ui_key_toggle']      = 'Toggle key',
    ['ui_key_menu']        = 'Open maker',
    ['ui_key_menu_cmd']    = 'or use /%{cmd}',

    -- NUI: style
    ['ui_type']            = 'Crosshair type',
    ['ui_type_hint']       = 'The base shape. Every type uses your colors and sizes.',
    ['ui_length']          = 'Line length',
    ['ui_length_hint']     = 'Length of each crosshair line.',
    ['ui_thickness']       = 'Thickness',
    ['ui_thickness_hint']  = 'Width of the lines.',
    ['ui_gap']             = 'Gap',
    ['ui_gap_hint']        = 'Empty space in the middle.',
    ['ui_sharpness']       = 'Sharpness',
    ['ui_sharpness_hint']  = '100 = razor sharp. Lower it for a soft glow look.',
    ['ui_rounded']         = 'Rounded ends',
    ['ui_rounded_hint']    = 'Round the line caps and the dot.',
    ['ui_circle_radius']   = 'Circle radius',
    ['ui_circle_thickness'] = 'Circle thickness',
    ['ui_dynamic']         = 'Dynamic gap',
    ['ui_dynamic_enable']  = 'Enable dynamic gap',
    ['ui_dynamic_hint']    = 'The crosshair opens up while you shoot or move, like in shooters.',
    ['ui_dynamic_fire']    = 'Expand on fire',
    ['ui_dynamic_fire_hint'] = 'Extra gap added while shooting.',
    ['ui_dynamic_move']    = 'Expand on move',
    ['ui_dynamic_move_hint'] = 'Extra gap added while moving.',

    -- NUI: colors
    ['ui_color']           = 'Main color',
    ['ui_color_hint']      = 'Color of the lines, circle and shapes.',
    ['ui_opacity']         = 'Opacity',
    ['ui_opacity_hint']    = 'Overall crosshair transparency.',
    ['ui_outline']         = 'Outline',
    ['ui_outline_enable']  = 'Enable outline',
    ['ui_outline_enable_hint'] = 'A contour around every shape so the crosshair reads on any background.',
    ['ui_outline_color']   = 'Outline color',
    ['ui_outline_thickness'] = 'Outline thickness',
    ['ui_outline_opacity'] = 'Outline opacity',

    -- NUI: dot
    ['ui_dot_enable']      = 'Show center dot',
    ['ui_dot_enable_hint'] = 'A dot in the exact center of the screen.',
    ['ui_dot_size']        = 'Dot size',
    ['ui_dot_opacity']     = 'Dot opacity',
    ['ui_dot_maincolor']   = 'Use main color',
    ['ui_dot_maincolor_hint'] = 'Off = pick a separate color for the dot.',
    ['ui_dot_color']       = 'Dot color',
    ['ui_dot_note']        = 'With the Dot type, the dot IS the whole crosshair.',

    -- NUI: scope
    ['ui_scope_enable']    = 'Custom scope',
    ['ui_scope_enable_hint'] = 'Replace aiming with a sniper-style scope overlay with zoom.',
    ['ui_scope_weapons']   = 'Works with',
    ['ui_scope_snipers']   = 'Snipers only',
    ['ui_scope_all']       = 'All guns',
    ['ui_scope_style']     = 'Scope style',
    ['ui_scope_color']     = 'Reticle color',
    ['ui_scope_opacity']   = 'Reticle opacity',
    ['ui_scope_thickness'] = 'Reticle thickness',
    ['ui_scope_dot']       = 'Center dot',
    ['ui_scope_dot_size']  = 'Center dot size',
    ['ui_scope_rings']     = 'Rings',
    ['ui_scope_rings_hint'] = 'Concentric circles drawn on the reticle.',
    ['ui_scope_vignette']  = 'Tunnel size',
    ['ui_scope_vignette_hint'] = 'How much of the screen edge is blacked out.',
    ['ui_zoom']            = 'Zoom',
    ['ui_zoom_min']        = 'Min zoom',
    ['ui_zoom_max']        = 'Max zoom',
    ['ui_zoom_step']       = 'Zoom step',
    ['ui_zoom_default']    = 'Starting zoom',
    ['ui_zoom_indicator']  = 'Show zoom indicator',
    ['ui_zoom_indicator_hint'] = 'Display the current zoom at the bottom of the scope.',
    ['ui_zoom_remember']   = 'Remember zoom',
    ['ui_zoom_remember_hint'] = 'Keep your last zoom level between aims.',
    ['ui_steady']          = 'Hold breath',
    ['ui_steady_hint']     = 'Hold Shift while scoped to steady your aim. The air bar shows how long you can hold.',
    ['ui_scope_howto']     = 'Aim to scope in. Scroll the mouse wheel to zoom.',

    -- NUI: feedback (hit confirm / ammo alert / threat tint)
    ['ui_sec_feedback']    = 'Feedback',
    ['ui_sec_feedback_sub'] = 'Hit flashes, ammo and target assists.',
    ['ui_hitconfirm']      = 'Hit confirm',
    ['ui_hitconfirm_enable'] = 'Enable hit confirm',
    ['ui_hitconfirm_enable_hint'] = 'The reticle flashes an X when your shot lands. A takedown flashes bigger, in its own color.',
    ['ui_hitconfirm_size'] = 'Flash size',
    ['ui_hitconfirm_maincolor'] = 'Use main color',
    ['ui_hitconfirm_maincolor_hint'] = 'Off = pick a separate color for the flash.',
    ['ui_hitconfirm_color'] = 'Hit color',
    ['ui_hitconfirm_killcolor'] = 'Takedown color',
    ['ui_ammoalert']       = 'Ammo alert',
    ['ui_ammoalert_enable'] = 'Enable ammo alert',
    ['ui_ammoalert_enable_hint'] = 'A magazine chip pulses under the crosshair while you aim with a nearly empty clip.',
    ['ui_ammoalert_threshold'] = 'Low clip threshold',
    ['ui_ammoalert_threshold_hint'] = 'The alert starts when the clip drops to this share of its size.',
    ['ui_threattint']      = 'Threat tint',
    ['ui_threattint_enable'] = 'Enable threat tint',
    ['ui_threattint_enable_hint'] = 'The crosshair switches color while you aim at a living character.',
    ['ui_threattint_color'] = 'Tint color',
    ['ui_test_hit']        = 'Hit',
    ['ui_test_kill']       = 'Takedown',
    ['ui_sim_lowammo']     = 'Low clip',
    ['ui_sim_threat']      = 'Hostile',
    ['ui_feedback_sim']    = 'Try it',

    -- NUI: sketchpad
    ['ui_sec_sketch']      = 'Sketchpad',
    ['ui_sec_sketch_sub']  = 'Draw your own crosshair by hand.',
    ['ui_sketch_use']      = 'Use my sketch',
    ['ui_sketch_use_hint'] = 'Show the drawing below as your crosshair. Turn off to go back to the standard shapes.',
    ['ui_sketch_canvas']   = 'Canvas',
    ['ui_sketch_tool']     = 'Tool',
    ['ui_sketch_tool_hint'] = 'Draw new strokes, or rub out the parts you do not want.',
    ['ui_sketch_tool_draw'] = 'Pen',
    ['ui_sketch_tool_erase'] = 'Rubber',
    ['ui_sketch_brush']    = 'Brush size',
    ['ui_sketch_eraser']   = 'Rubber size',
    ['ui_sketch_mirror']   = 'Symmetry',
    ['ui_sketch_mirror_hint'] = 'Strokes and rubbing are both mirrored while you work.',
    ['ui_sketch_mirror_off'] = 'Free',
    ['ui_sketch_mirror_x'] = 'Left-right',
    ['ui_sketch_mirror_y'] = 'Up-down',
    ['ui_sketch_mirror_quad'] = 'Fourway',
    ['ui_sketch_undo']     = 'Undo',
    ['ui_sketch_clear']    = 'Clear',
    ['ui_sketch_empty']    = 'Click and drag on the canvas to draw.',
    ['ui_sketch_color_note'] = 'Strokes use your main color from the Colors tab.',
    ['ui_sketch_strokes']  = 'strokes',
    ['ui_share_sketch']    = 'Hand-drawn crosshairs are too detailed for a share code. Save them as a profile instead.',

    -- NUI: preview
    ['ui_preview']         = 'Live Preview',
    ['ui_preview_off']     = 'Crosshair is OFF',
    ['ui_sim_fire']        = 'Simulate fire',
    ['ui_sim_move']        = 'Moving',
    ['ui_sim_need_dynamic'] = 'Enable Dynamic gap in Style to simulate.',
    ['ui_scope_hint_preview'] = 'In game: scroll to zoom while aiming.',

    -- NUI: profiles & presets
    ['ui_presets']         = 'Presets',
    ['ui_presets_hint']    = 'One-click starting points. Applying overwrites your current crosshair.',
    ['ui_preset_tip']      = 'Apply this preset',
    ['ui_preset_confirm_title'] = 'Apply preset?',
    ['ui_preset_confirm_body']  = 'Your current crosshair is replaced by this preset. Saved profiles are kept.',
    ['ui_profiles']        = 'My profiles',
    ['ui_profiles_hint']   = 'Save your favorite crosshairs and switch anytime.',
    ['ui_profile_name']    = 'Profile name…',
    ['ui_profile_save']    = 'Save current',
    ['ui_profile_load']    = 'Load',
    ['ui_profile_delete_title'] = 'Delete profile?',
    ['ui_profile_delete_body']  = '%{name} is removed permanently.',
    ['ui_profiles_empty']  = 'No profiles yet. Design something and save it.',
    -- NUI: admin panel
    ['ui_admin_title']     = 'Crosshair',
    ['ui_admin_subtitle']  = 'Admin',
    ['ui_admin_hint']      = 'Everything here applies to every player on the server, live.',
    ['ui_admin_save']      = 'Save & apply',
    ['ui_admin_saved']     = 'Applied',
    ['ui_admin_unsaved']   = 'Unsaved changes',
    ['ui_admin_reset']     = 'Reset to config',
    ['ui_admin_reset_title'] = 'Reset to the file config?',
    ['ui_admin_reset_body']  = 'Everything goes back to what sh.config.lua says. Your saved admin config is deleted. Player crosshairs are kept.',
    ['ui_admin_sec_features'] = 'Features',
    ['ui_admin_sec_features_sub'] = 'Switch whole features off. They vanish from every player UI.',
    ['ui_admin_sec_types'] = 'Crosshair types',
    ['ui_admin_sec_types_sub'] = 'Which shapes players may pick.',
    ['ui_admin_sec_scope'] = 'Scope rules',
    ['ui_admin_sec_scope_sub'] = 'Zoom caps, scope styles and hold breath.',
    ['ui_admin_sec_limits'] = 'Limits',
    ['ui_admin_sec_limits_sub'] = 'The range of every slider in the maker.',
    ['ui_admin_sec_general'] = 'General',
    ['ui_admin_sec_general_sub'] = 'Command, keys, vanilla reticle, profiles and debug.',
    ['ui_admin_sec_weapons'] = 'Weapons',
    ['ui_admin_sec_weapons_sub'] = 'Single guns that should behave differently.',

    -- NUI: admin panel — weapons
    ['ui_admin_weapons_how'] = 'How it works',
    ['ui_admin_weapons_how_body'] = 'Every gun follows its weapon class (its GTA weapon group). Add a gun below to give that one gun a different class, or to let it use the scope like a sniper rifle.',
    ['ui_admin_weapons_link'] = 'Weapon names:',
    ['ui_admin_weapons_overrides'] = 'Weapon overrides',
    ['ui_admin_weapons_overrides_hint'] = 'One row per gun. Everything not listed here follows its class.',
    ['ui_admin_weapons_noop'] = 'A gun left on Automatic for both is dropped when you save: it changes nothing.',
    ['ui_admin_weapons_placeholder'] = 'WEAPON_MARKSMANRIFLE',
    ['ui_admin_weapons_add'] = 'Add gun',
    ['ui_admin_weapons_empty'] = 'No gun breaks the rules yet.',
    ['ui_admin_weapons_gun'] = 'Gun',
    ['ui_admin_weapons_class'] = 'Class',
    ['ui_admin_weapons_class_auto'] = 'Automatic',
    ['ui_admin_weapons_scope'] = 'Scope',
    ['ui_admin_weapons_scope_auto'] = 'Automatic',
    ['ui_admin_weapons_scope_sniper'] = 'Counts as sniper',
    ['ui_admin_weapons_scope_allowed'] = 'Can scope',
    ['ui_admin_weapons_scope_blocked'] = 'Never scopes',

    -- NUI: admin panel — weapon groups (scope rules)
    ['ui_admin_groups']    = 'Weapon groups',
    ['ui_admin_groups_hint'] = 'Which kinds of gun may use the scope, and which ones count as sniper rifles. Single guns can break these rules in the Weapons tab.',
    ['ui_admin_group_scope'] = 'Can scope',
    ['ui_admin_group_sniper'] = 'Sniper',

    -- NUI: admin panel — command & keys
    ['ui_admin_access']    = 'Command & keys',
    ['ui_admin_access_hint'] = 'How players open the maker. Switch both off and they cannot open it at all.',
    ['ui_admin_cmd']       = 'Chat command',
    ['ui_admin_cmd_hint']  = 'What players type to open the maker.',
    ['ui_admin_key_toggle'] = 'Key: turn the crosshair on/off',
    ['ui_admin_key_toggle_hint'] = 'A key that shows and hides the crosshair.',
    ['ui_admin_key_menu']  = 'Key: open the maker',
    ['ui_admin_key_menu_hint'] = 'A key that opens the crosshair maker, so players do not have to type the command.',
    ['ui_admin_keys_note'] = 'Players can always rebind these keys themselves, in GTA Settings -> Key Bindings -> FiveM.',
    ['ui_admin_keys_link'] = 'Key names:',
    ['ui_admin_keys_restart'] = 'Switching these off works right away. A new command name or a new key reaches players when they reconnect.',
    ['ui_admin_styles']    = 'Scope styles',
    ['ui_admin_showmodes'] = 'Show modes',
    ['ui_admin_showmodes_hint'] = 'Which "Show crosshair" options players may choose.',
    ['ui_admin_zoomcap']   = 'Max zoom',
    ['ui_admin_zoomcap_hint'] = 'Hard cap: no player can zoom past this, whatever they set.',
    ['ui_admin_basemag']   = 'Overlay magnification',
    ['ui_admin_basemag_hint'] = 'How strong "x1" is on the overlay scope (non-sniper guns).',
    ['ui_admin_native']    = 'Native sniper scope',
    ['ui_admin_native_hint'] = 'Snipers keep GTA\'s own scope view. Off = the custom overlay scope on snipers too.',
    ['ui_admin_invehicle'] = 'Scope in vehicles',
    ['ui_admin_invehicle_hint'] = 'Allow the scope while the player sits in a vehicle.',
    ['ui_admin_breath']    = 'Hold breath',
    ['ui_admin_breath_hint'] = 'Players can hold Shift to steady the scope.',
    ['ui_admin_breath_dur'] = 'Breath duration',
    ['ui_admin_breath_rec'] = 'Breath recovery',
    ['ui_admin_hide']      = 'Hide GTA reticle',
    ['ui_admin_hide_hint'] = 'When the vanilla crosshair (and the sniper scope reticle) is hidden.',
    ['ui_admin_hide_always'] = 'Always',
    ['ui_admin_hide_enabled'] = 'When custom is on',
    ['ui_admin_hide_never'] = 'Never',
    ['ui_admin_maxprofiles'] = 'Profiles per player',
    ['ui_admin_debug']     = 'Debug mode',
    ['ui_admin_debug_hint'] = 'Console prints and the state chip on every player overlay. Leave off in production.',
    ['ui_admin_min']       = 'Min',
    ['ui_admin_max']       = 'Max',
    ['ui_admin_limit_row_reset'] = 'Back to the config value',
    ['ui_admin_enabled_count'] = '%{on} of %{total} enabled',
    ['ui_admin_last_one']  = 'At least one has to stay on.',
    ['ui_admin_feat_dynamicGap'] = 'Dynamic gap',
    ['ui_admin_feat_dynamicGap_sub'] = 'The crosshair opens up while firing or moving.',
    ['ui_admin_feat_hitConfirm'] = 'Hit confirm',
    ['ui_admin_feat_hitConfirm_sub'] = 'X flash on the reticle when a shot lands.',
    ['ui_admin_feat_ammoAlert'] = 'Ammo alert',
    ['ui_admin_feat_ammoAlert_sub'] = 'Magazine chip pulses on a nearly empty clip.',
    ['ui_admin_feat_threatTint'] = 'Threat tint',
    ['ui_admin_feat_threatTint_sub'] = 'Crosshair recolors while aimed at a person.',
    ['ui_admin_feat_sketchpad'] = 'Sketchpad',
    ['ui_admin_feat_sketchpad_sub'] = 'Players draw their own freehand crosshair.',
    ['ui_admin_feat_perWeapon'] = 'Per weapon',
    ['ui_admin_feat_perWeapon_sub'] = 'A different crosshair per weapon class.',
    ['ui_admin_feat_scope'] = 'Custom scope',
    ['ui_admin_feat_scope_sub'] = 'The sniper-style scope with mouse-wheel zoom.',
    ['ui_admin_feat_profiles'] = 'Profiles',
    ['ui_admin_feat_profiles_sub'] = 'Players can save and load named crosshairs.',
    ['ui_admin_feat_presets'] = 'Presets',
    ['ui_admin_feat_presets_sub'] = 'The one-click preset grid.',
    ['ui_admin_feat_shareCodes'] = 'Share codes',
    ['ui_admin_feat_shareCodes_sub'] = 'Export and import crosshairs as DHX codes.',

    ['ui_share']           = 'Share code',
    ['ui_share_hint']      = 'Export your crosshair as a code and share it with friends.',
    ['ui_export']          = 'Export',
    ['ui_export_tip']      = 'Copy your crosshair code to the clipboard',
    ['ui_copied']          = 'Copied!',
    ['ui_import']          = 'Import',
    ['ui_import_title']    = 'Import a crosshair code',
    ['ui_import_body']     = 'Paste a code you got from another player.',
    ['ui_import_placeholder'] = 'Paste the code here…',
    ['ui_import_error']    = 'That code could not be read. Check you copied all of it.',
    ['ui_delete']          = 'Delete',
}
